version: "3.8"
services:
  oracle-12c:
    image: tekintian/oracle12c
    container_name: oracle-12c
    privileged: true
    restart: always
    network_mode: "bridge"
    environment:
      TZ: "Asia/Shanghai"
      DBCA_TOTAL_MEMORY: 1024
    ports:
      - 1521:1521
      - 1520:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/u01/app/oracle

####################      
# 连接参数如下
# hostname: localhost
# port: 1521
# sid: xe
# service name: xe
# username: system
# password: oracle
####################
