version: '3.3'
services:
  tomcat8-5-66:
    image: tomcat:8.5.66
    container_name: tomcat8-5-66
    restart: always
    network_mode: 'bridge'
    environment:
      TZ: Asia/Shanghai
    ports:
      - 9090:8080
    volumes:
      - ./webapps:/usr/local/tomcat/webapps
      - ./conf:/usr/local/tomcat/conf
