version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:2.414.1-lts-jdk11
    container_name: jenkins
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - "8083:8080"
      - "50000:50000"
    volumes:
      - $PWD/data:/var/jenkins_home
