version: '3.3'
services:
  vsftpd:
    image: fauria/vsftpd
    container_name: fauria-vsftpd
    restart: always
    network_mode: 'bridge'
    environment:
      - FTP_USER=admin
      - FTP_PASS=123456
      - PASV_ADDRESS=127.0.0.1
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - ./data/home/vsftpd:/home/vsftpd