version: '3.8'
services:
  postgres-14-2:
    image: postgres:14.2
    container_name: postgres-14-2
    restart: always
    environment:
      TZ: Asia/Shanghai
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - kong-net
networks:
  kong-net:
    external: true
