version: '3.8'
services:
  postgres:
    image: postgres:15.3
    container_name: postgres
    restart: always
    network_mode: bridge
    environment:
      TZ: Asia/Shanghai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - ./data/postgresql:/var/lib/postgresql
    ports:
      - 5432:5432
