version: '3.8'
services:
  iems-sqlserver:
    image: registry.cn-hangzhou.aliyuncs.com/cnnit/iems-sqlserver:1.0.0
    container_name: iems-sqlserver
    restart: always
    environment:
      TZ: 'Asia/Shanghai'
      #接受最终用户许可协议
      ACCEPT_EULA: 'Y'
      #SA用户密码
      SA_PASSWORD: 'password.com'
    ports:
      - 1433:1433
    networks:
      - iems
  sy-iems:
    image: registry.cn-hangzhou.aliyuncs.com/cnnit/sy-iems:1.0.0
    container_name: sy-iems
    restart: always
    environment:
      TZ: 'Asia/Shanghai'
      #sqlserver数据库地址
      SQLSERVER_HOST: 'sqlserver'
      #iems后台部署地址
      IEMS_SERVER_HOST: '192.168.1.135'
    ports:
      - 8080:8080
    networks:
      - iems
    links:
      - iems-sqlserver:sqlserver
    depends_on:
      - iems-sqlserver
  iems-nginx:
    image: registry.cn-hangzhou.aliyuncs.com/cnnit/iems-nginx:1.0.0
    container_name: iems-nginx
    restart: always
    environment:
      TZ: 'Asia/Shanghai'
      NGINX_PORT: '80'
      #进出口后台地址
      IEMS_HOST: '192.168.1.135:8080'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 9090:80
    networks:
      - iems
networks:
  iems:
    external: true