version: '3.8'
services:
  iems-jt-oracle11g:
    image: registry.cn-hangzhou.aliyuncs.com/cnnit/iems-jt-oracle:11g
    container_name: iems-jt-oracle11g
    privileged: true
    restart: always
    environment:
      TZ: 'Asia/Shanghai'
      DBCA_TOTAL_MEMORY: 16192
    ports:
      - 1521:1521
    networks:
      - iemsjt
  iems-jt-system:
    image: registry.cn-hangzhou.aliyuncs.com/cnnit/iems-jt-system:1.0.0
    container_name: iems-jt-system
    restart: always
    environment:
      TZ: 'Asia/Shanghai'
      DATABASE_HOST: 'iems-jt-oracle11g'
    ports:
      - 8081:8081
    links:
      - iems-jt-oracle11g:iems-jt-oracle11g
    depends_on:
      - iems-jt-oracle11g
    networks:
      - iemsjt
  iems-jt-nginx:
    image: registry.cn-hangzhou.aliyuncs.com/cnnit/iems-jt-nginx:1.0.0
    container_name: iems-jt-nginx
    restart: always
    environment:
      TZ: 'Asia/Shanghai'
      NGINX_PORT: '9091'
    ports:
      - 9091:9091
    links:
      - iems-jt-system:iems-jt-system
    networks:
      - iemsjt
networks:
  iemsjt:
    external: true
