version: '3.3'
services:
  zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql
    container_name: zabbix-server-mysql
    restart: always
    environment:
      TZ: "Asia/Shanghai"
      DB_SERVER_HOST: "192.168.0.200"
      MYSQL_USER: "username"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
      DB_SERVER_PORT: "3306"
      MYSQL_DATABASE: "zabbix"
    ports:
      - 10051:10051
    volumes:
      - ./data/zbox:/opt/zbox/

  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql
    container_name: zabbix-web-nginx-mysql
    environment:
      TZ: "Asia/Shanghai"
      DB_SERVER_HOST: "192.168.0.200"
      MYSQL_USER: "username"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
      DB_SERVER_PORT: "3306"
      MYSQL_DATABASE: "zabbix"
      ZBX_SERVER_NAME: "192.168.0.200"
    ports:
      - 60001:80
    depends_on:
      - zabbix-server-mysql
