version: '3.3'

services:

# mysql service for zentao
  zentao-mariadb:
    image: mariadb:10.6
    container_name: zentao-mysql
    network_mode: 'bridge'
    restart: always
    ports:
      - '3307:3306'
    volumes:
      - zentao_db:/var/lib/mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=password.com
      - MYSQL_DATABASE=zentao

# redis service for zentao
#  zentao-redis:
#    image: redis:3.2.12-alpine3.8
#    container_name: zentao-redis
#    networks:
#      - zentao-net

# zentao service
  zentao:
    image: hub.zentao.net/app/zentao:18.9
    container_name: zentao
    network_mode: 'bridge'
    restart: always
    ports:
      - '61000:80'
    volumes:
      - zentao_data:/data
    depends_on:
      - zentao-mariadb
    environment:
      - TZ=Asia/Shanghai
      - ZT_MYSQL_HOST=zentao-mysql
      - ZT_MYSQL_PORT=3307
      - ZT_MYSQL_USER=root
      - ZT_MYSQL_PASSWORD=password.com
      - ZT_MYSQL_DB=zentao
     # - PHP_SESSION_TYPE=redis
     # - PHP_SESSION_PATH=tcp://zentao-redis:6379
     # - PHP_REDIS_SENTINEL=1  
      - PHP_MAX_EXECUTION_TIME=120
      - PHP_MAX_INPUT_VARS=2000
      - PHP_MEMORY_LIMIT=512M
      - PHP_POST_MAX_SIZE=128M
      - PHP_UPLOAD_MAX_FILESIZE=128M
      - LDAP_ENABLED=false
      - SMTP_ENABLED=false
      - SMTP_FROMNAME=禅道旗舰版
      - SMTP_HOST=192.168.50.182
      - SMTP_PORT=25
      - SMTP_USER=root@demo.com
      - SMTP_PASS=password
      - APP_DEFAULT_PORT=80
      - APP_DOMAIN=zentao.demo.com
      - PROTOCOL_TYPE=http
      - EASYSOFT_DEBUG=true
      - DEBUG=1
      - IS_CONTAINER=true
      - LINK_GIT=false
      - GIT_TYPE=gitea
      - GIT_INSTANCE_NAME=demo
      - GIT_USERNAME=user
      - GIT_PASSWORD=password
      - GIT_DOMAIN=https://git.demo.com
      # - GIT_TOKEN=token-example
      - LINK_CI=false
      - CI_TYPE=jenkins
      - CI_URL=https://jenkins.demo.com
      - CI_USERNAME=user
      - CI_PASSWORD=password
      # - CI_TOKEN=token-example
      - LINK_SCAN=false
      - SCAN_TYPE=sonarqube
      - SCAN_URL=https://sonarqube.demo.com
      - SCAN_USERNAME=user
      - SCAN_PASSWORD=password