version: '3.8'
services:
  txl-natapp:
    image: registry.cn-hangzhou.aliyuncs.com/txlhub/natapp:yfhx-tcp200
    container_name: txl-natapp
    restart: always
    network_mode: 'bridge'
    environment:
      TZ: 'Asia/Shanghai'
    ports:
      - 60002:80
