version: '3.3'
services:
  mysql-5-7-34:
    image: mysql:5.7.34
    container_name: mysql-5.7.34
    restart: always
    network_mode: 'bridge'
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: shanhong
    command:
      --character-set-server=utf8
      --max_connections=2000
    volumes:
      - ./data/var/lib/mysql:/var/lib/mysql
      - ./data/etc/mysql:/etc/mysql
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3306:3306