version: '3.3'
services:
  node-exporter:
    image: 'prom/node-exporter'
    hostname: node-exporter
    container_name: node-exporter
    restart: always
    network_mode: bridge
    ports:
      - 9091:9100
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
