version: '3'
services:
  sonar:
    image: sonarqube:9.5.0-community
    container_name: sonar
    volumes:
      - ./data/extensions:/opt/sonarqube/extensions
      - ./data/logs:/opt/sonarqube/logs
      - ./data/data:/opt/sonarqube/data
      - ./data/conf:/opt/sonarqube/conf
    ports:
      - 19000:9000
    command:
      - -Dsonar.ce.javaOpts=-Xmx2048m
      - -Dsonar.web.javaOpts=-Xmx2048m
      - -Dsonar.web.context=/sonar
    environment:
      SONARQUBE_JDBC_USERNAME: yfhx
      SONARQUBE_JDBC_PASSWORD: yfhx2020
      SONARQUBE_JDBC_URL: jdbc:postgresql://192.168.0.211:5432/sonar
