version: '3.8'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    container_name: es01
    restart: always
    hostname: es01
    network_mode: 'bridge'
    environment:
      - TZ="Asia/Shanghai"
      - node.name=es01
      - cluster.name=es-docker-cluster
      #- discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #- ./data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
