version: '3.8'

services:
  kooder:
    image: registry.cn-hangzhou.aliyuncs.com/devops_hu/kooder:v1.0.1
    container_name: kooder
    restart: always
    network_mode: bridge
    privileged: true
    volumes:
      - ./kooder.properties:/root/kooder.properties:ro
    ports:
      - 9910:8080