version: '3.3'
services:
  nginx:
    image: nginx:1.18
    container_name: nginx-1.18
    restart: always
    network_mode: 'bridge'
    environment:
#      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    ports:
      - 9091:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
