version: "3.3"
services:
  flowable-ui:
    image: flowable/flowable-ui:6.7.2
    container_name: flowable-ui
    restart: always
    network_mode: "bridge"
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - "8080:8080"
    volumes:
      - ./data/app:/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    external_links:
      - mysql-5.7.34