version: "3.8"
services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    container_name: zookeeper
    restart: always
    environment:
      TZ: 'Asia/Shanghai'
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zookeeper_data:/bitnami
    ports:
      - "2181:2181"
    healthcheck:
      test: [ "CMD-SHELL", "ps -ef|grep :zookeeper || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 5

  kafka:
    image: docker.io/bitnami/kafka:3.4
    container_name: kafka
    restart: always
    environment:
      - TZ='Asia/Shanghai'
      - KAFKA_BROKER_ID=0
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://ip:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_LOG_RETENTION_HOURS=120
      - KAFKA_MESSAGE_MAX_BYTES=10000000
      - KAFKA_REPLICA_FETCH_MAX_BYTES=10000000
      - KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS=60000
      - KAFKA_NUM_PARTITIONS=3
      - KAFKA_DELETE_RETENTION_MS=1000
    ports:
      - "9092:9092"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./kafka_data:/bitnami
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper
    healthcheck:
      test: [ "CMD-SHELL", "ps -ef|grep :kafka || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 5

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: always
    environment:
      - TZ='Asia/Shanghai'
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8080:8080
    links:
      - kafka:kafka
    healthcheck:
      test: [ "CMD-SHELL", "netstat -tnlp|grep :8080 || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 5
