version: "3.3"
services:
  flowable-rest:
    image: flowable/flowable-rest:6.7.2
    container_name: flowable-rest
    restart: always
    network_mode: "bridge"
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - "8080:8080"
    volumes:
      - ./data/app:/app
      - ./data/usr/share/fonts:/usr/share/fonts
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    external_links:
      - mysql-5.7.34
