version: '3.8'
services:
  nexus3:
    image: sonatype/nexus3:3.56.0
    restart: always
    container_name: nexus3
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - 8081:8081
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/nexus-data
