version: '3.8'
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.8.13
    container_name: homepage
    restart: unless-stoppe
    environment:
      PUID: 1000 # optional, your user id
      PGID: 1000 # optional, your group id
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
