version : '3.3'
services:
  wdh-minio:
    container_name: wdh-minio
    image: minio/minio:RELEASE.2022-04-12T06-55-35Z.fips
    network_mode: 'bridge'
    restart: always
    environment:
      - MINIO_ROOT_USER=yfhx
      - MINIO_ROOT_PASSWORD=yfhx753951
      - MINIO_ACCESS_KEY=yfhx
      - MINIO_SECRET_KEY=yfhx753951
    volumes:
      - ./data/data:/data
      - ./data/config:/root/.minio
    command: server /data  --console-address ':9001'
    ports:
      - "9000:9000"
      - "9001:9001"