version: '3.8'
services:
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2023-06-23T20-26-00Z.fips
    network_mode: 'bridge'
    restart: always
    environment:
      - TZ="Asia/Shanghai"
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=password
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/data:/data
      - ./data/config:/root/.minio
    command: server /data  --console-address ':9001'
    ports:
      - "9000:9000"
      - "9001:9001"
