version: '3.8'
services:
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus
    restart: always
    network_mode: 'bridge'
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - 9090:9090
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/prometheus:/etc/prometheus

scrape_configs:
  - job_name: 'yfhx-devops1210'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ '192.168.0.200:60006' ]
