version: '3.8'
services:
  kong-gateway:
    image: kong/kong-gateway:2.8.0.0-alpine
    container_name: kong-gateway
    restart: always
    environment:
      TZ: Asia/Shanghai
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres-14-2
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: password
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 8002:8002
      - 8445:8445
      - 8003:8003
      - 8004:8004
    depends_on:
      - postgres-14-2
    links:
      - postgres-14-2
    networks:
      - kong-net
networks:
  kong-net:
    external: true


  
  

# 准备kong数据库
# docker run --rm --network=kong-net \
#  -e "KONG_DATABASE=postgres" \
#  -e "KONG_PG_HOST=postgres-14-2" \
#  -e "KONG_PG_PASSWORD=password" \
# kong/kong-gateway:2.8.0.0-alpine kong migrations bootstrap