version: '3.3'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:7.12.0
    container_name: logstash
    restart: always
    network_mode: 'bridge'
    environment:
      TZ: 'Asia/Shanghai'
      HTTP_HOST: 0.0.0.0
      XPACK_MONITORING_ELASTICSEARCH_HOSTS: http://192.168.0.200:9200
    ports:
      - 9600:9600
    volumes:
      - ./data/logstash:/usr/share/logstash
