version: '3.8'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:8.8.1
    container_name: logstash
    restart: always
    network_mode: 'bridge'
    environment:
      TZ: "Asia/Shanghai"
      HTTP_HOST: 0.0.0.0
      XPACK_MONITORING_ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 9600:9600
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/logstash:/usr/share/logstash
