version: '3.3'
services:
  mongodb4-0:
    image: mongo:4.0
    container_name: mongodb4-0
    restart: always
    network_mode: 'bridge'
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: shanhong
    volumes:
      - ./data/db:/data/db
      - ./data/mongod.conf.orig:/etc/mongod.conf.orig
    ports:
      - 27017:27017

  mongo-express:
    depends_on:
      - mongodb4-0
    image: mongo-express
    container_name: mongo-express
    restart: always
    network_mode: 'bridge'
    ports:
      - 27018:8081
    environment:
      TZ: Asia/Shanghai
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: shanhong
      ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"
      ME_CONFIG_MONGODB_SERVER: "mongodb4-0"
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: "root"
      ME_CONFIG_BASICAUTH_PASSWORD: "shanhong"