version: '3.8'
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.21.3
    container_name: uptime-kuma
    restart: always
    network_mode: 'bridge'
    environment:
      TZ: 'Asia/Shanghai'
    ports:
      - 3001:3001
    volumes:
      - ./data:/app/data
