version: '3.3'
services:
  centos7:
    image: registry.cn-hangzhou.aliyuncs.com/txlhub/centos:7
    container_name: centos7
    restart: always
    network_mode: 'bridge'
    environment:
      - TZ=Asia/Shanghai
    command: /bin/bash -c "/usr/sbin/sshd -d"
    ports:
      - '2290:22'
      - '9400:8080'
# 用户名和密码：root/root
### centos7解决 docker Failed to get D-Bus connection 报错
# sudo docker run --privileged -d -ti -e "container=docker" centos  /usr/sbin/init
