version: '3.8'
services:
  confluence:
    image: registry.cn-hangzhou.aliyuncs.com/txlhub/confluence:7.13.7
    container_name: confluence
    restart: always
    network_mode: bridge
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./data/confluence:/var/atlassian/application-data/confluence
      - ./data/opt-confluence/confluence:/opt/atlassian/confluence
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8090:8090
      - 8091:8091